In [1]:
import pandas as pd
import psycopg2

In [10]:
start = "2014-01-01"
end = "2020-08-20"
conn = psycopg2.connect(host="slave",
                        database="testdb1",
                        user="postgres",
                        password="reallyStrongPwd123")
cursor = conn.cursor()
symbols = ("MSFT", "GOOGL", "FB")
query2 = f""" SELECT * from incertae."StockData" where symbol in {symbols} and date between '{start}' AND '{end}' """
df = pd.read_sql_query(query2, con=conn)
df.set_index(["date", "symbol"], inplace=True)
df = df.unstack()

In [11]:
df.swaplevel()
df

             adj_close                                close                                 high  ...         low        open                               volume
symbol              FB        GOOGL        MSFT          FB        GOOGL        MSFT          FB  ...        MSFT          FB        GOOGL        MSFT          FB      GOOGL        MSFT
date                                                                                              ...
2014-01-02   54.709999   557.117126   32.215286   54.709999   557.117126   37.160000   55.220001  ...   37.099998   54.830002   558.288269   37.349998  43195500.0  3639100.0  30632200.0
2014-01-03   54.560001   553.053040   31.998550   54.560001   553.053040   36.910000   55.650002  ...   36.599998   55.020000   558.058044   37.200001  38246200.0  3330000.0  31134800.0
2014-01-06   57.200001   559.219238   31.322340   57.200001   559.219238   36.130001   57.259998  ...   36.110001   54.419998   557.062073   36.849998  68852600.0  3535000.0  43603700.0
2014-01-07   57.919998   570.000000   31.565083   57.919998   570.000000   36.410000   58.549999  ...   36.209999   57.700001   563.063049   36.330002  77207400.0  5100000.0  35802800.0
2014-01-08   58.230000   571.186157   31.001577   58.230000   571.186157   35.759998   58.410000  ...   35.580002   57.599998   573.573547   36.000000  56682400.0  4480500.0  59971700.0
...                ...          ...         ...         ...          ...         ...         ...  ...         ...         ...          ...         ...         ...        ...         ...
2020-08-14  261.239990  1504.630005  208.396240  261.239990  1504.630005  208.899994  262.649994  ...  207.509995  262.309998  1513.609985  208.759995  14792700.0  1097100.0  17958900.0
2020-08-17  261.160004  1516.239990  209.772919  261.160004  1516.239990  210.279999  264.100006  ...  208.919998  262.500000  1515.969971  209.600006  13351100.0   999500.0  20184800.0
2020-08-18  262.339996  1555.780029  210.979996  262.339996  1555.780029  211.490005  265.149994  ...  209.210007  260.950012  1526.119995  210.529999  18690400.0  1418900.0  21336200.0
2020-08-19  262.589996  1544.609985  209.699997  262.589996  1544.609985  209.699997  267.910004  ...  209.250000  261.390015  1552.489990  211.490005  23268600.0  1522800.0  27600900.0
2020-08-20  269.010010  1576.250000  214.580002  269.010010  1576.250000  214.580002  269.617310  ...  208.910004  261.500000  1539.969971  209.539993  20299688.0  1319131.0  26981478.0

[1671 rows x 18 columns]

In [7]:
df.groupby(level=1).to_dict()

AttributeError: 'DataFrameGroupBy' object has no attribute 'to_dict'

In [7]:
df.shape

(1671, 18)

In [200]:

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 100, df.shape[1]-1, 20, 1
w1 = np.random.randn(D_in,  H)
w2 = np.random.randn(H,D_out)
b1 = np.random.randn(H)
b2 = np.random.randn(D_out)
y= df1[('high', 'FB')].shift(1)
x=df1.drop(('high', 'FB'),axis=1)
y = y.fillna(0)
lr = 1e-5
for i in range(10):

    h=x.dot(w1) + b1
    h_relu = np.maximum(h,0)
    y_pred =( h_relu.dot(w2) + b2)[0]
    loss = np.square(y_pred-y).sum()


    grad_y_pred = 2.0 *(y_pred-y)
    grad_b2 = 2.0 * (y_pred-y).sum()
    grad_w2 = 2.0 * grad_y_pred.dot(h_relu)

    # hiden layer
    print(f"Gy^: {grad_y_pred.shape}, W2: {w2.shape}, GW2: {grad_w2.shape}, GB2: {grad_b2.shape}")
    print(f"GH: {grad_h.shape}, X: {x.shape},W1: {w1.shape} ,GW1: {grad_w1.shape}, B1: {b1.shape}, GB1: {grad_b1.shape}")
    print(pd.DataFrame(w2))
    grad_h_relu = pd.DataFrame( grad_y_pred).dot(pd.DataFrame( w2).T)
    grad_h  = grad_h_relu.copy()
    grad_h[grad_h<0] =0
    grad_w1 = x.T.dot(grad_h)
    grad_b1  = grad_h

    w2 = w2.flatten()
    w2 -= lr * grad_w2
    b2 -= lr * grad_b2

    w2 -= lr * grad_w2
    b2 -= lr * grad_b2

    w1 -= lr * grad_w1
    b1 -= lr * grad_b1.sum()

Gy^: (1671,), W2: (20, 1), GW2: (20,), GB2: ()
GH: (1671, 20), X: (1671, 17),W1: (17, 20) ,GW1: (17, 20), B1: (20,), GB1: (1671, 20)
           0
0  -0.315461
1  -0.763452
2   0.001125
3   0.854818
4  -2.204628
5  -1.109374
6   0.236728
7   0.210482
8   0.176026
9  -1.376825
10  0.083142
11 -1.003524
12 -1.068657
13  0.562389
14  0.562641
15  0.456866
16  0.442731
17 -1.608314
18 -0.410447
19 -0.320795
Gy^: (1671,), W2: (20,), GW2: (20,), GB2: ()
GH: (1671, 20), X: (1671, 17),W1: (17, 20) ,GW1: (17, 20), B1: (20,), GB1: (1671, 20)
               0
0   1.733592e+13
1   6.216187e+12
2   1.465563e+13
3  -9.166283e+12
4   2.121998e+12
5  -1.557215e+13
6   2.367278e-01
7  -2.247824e+12
8   1.760265e-01
9   1.806729e+13
10  1.253675e+12
11 -1.003524e+00
12  4.236110e+12
13 -3.660441e+13
14  3.346406e+13
15 -1.067567e+13
16  1.414956e+13
17  2.380767e+13
18  1.236754e+13
19 -3.207945e-01

ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'

np.reshape(grad_y_pred,(grad_y_pred.shape[0],1))
# Pandas is used instead of reshape, reshape didn't work

In [ ]:
grad_y_pred

(1671, 20)