In [7]:

import numpy as np
import pandas as pd
import pandas_ta as ta
import torch
import torch.nn  as nn
import torch.nn.functional as F
from torch.autograd import Variable
import psycopg2

import os
os.chdir("../")
from watchlist import Watchlist
import sys
from database.postgres_sql_connect import get_engine

# Websites

https://github.com/twopirllc/pandas-ta/blob/master/examples/PandasTA_Strategy_Examples.ipynb

https://github.com/twopirllc/pandas-ta/blob/master/examples/example.ipynb

# get data

In [69]:
symbs = pd.read_sql("""select * from incertae."Symbols" where sp500=True """, conn)

In [70]:
symbs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         0 non-null      object
 1   sp500      503 non-null    bool
 2   name       503 non-null    object
 3   symbol     503 non-null    object
 4   amex       365 non-null    object
 5   nasdaq     138 non-null    object
 6   marketcap  501 non-null    object
 7   sector     498 non-null    object
 8   industry   498 non-null    object
 9   nyse       0 non-null      object
 10  ipoyear    503 non-null    int64
dtypes: bool(1), int64(1), object(9)
memory usage: 39.9+ KB

In [71]:
def convert_currency_to_float(a):
    if a is None:
        return a
    else:
        b = a.translate(str.maketrans({'$': '', ',': ''}))
        return float(b)
symbs["marketcap"] =  symbs["marketcap"].apply(convert_currency_to_float)

In [75]:
selected_symbs = tuple(symbs.query('marketcap>100000')["symbol"].to_list())

In [78]:
ss="MSFT"

# Fetching lots of symbols

#### start = "2014-01-01"
end = "2020-08-20"
conn = psycopg2.connect(host="slave",
                        database="testdb1",
                        user="postgres",
                        password="reallyStrongPwd123")
cursor = conn.cursor()
symbols = ("MSFT", "GOOGL", "FB")
query3 = f""" SELECT * from incertae."stockdata" where symbol in {selected_symbs} and date between '{start}' AND '{end}' """

df = pd.read_sql_query(query3, con=conn)
df.set_index(["date", "symbol"], inplace=True)
# df.set_index("date", inplace=True)
# df = df.unstack()
# df.columns = df.columns.values

affb = df[df.index.get_level_values(1)=='FB'].droplevel("symbol",0)
affb = affb.sort_index()

In [81]:
start = "2020-05-01"
end = "2020-08-20"
conn = psycopg2.connect(host="slave",
                        database="testdb1",
                        user="postgres",
                        password="reallyStrongPwd123")
cursor = conn.cursor()
query2 = f""" SELECT * from incertae."stockdata" where symbol='{ss}' and date between '{start}' AND '{end}' """
df = pd.read_sql_query(query2, con=conn)
df.set_index("date", inplace=True)
# df = df.unstack()
# df.columns = df.columns.values

# pandas-ta

In [3]:

# Calculate Returns and append to the df DataFrame
df.ta.log_return(cumulative=True, append=True)
df.ta.percent_return(cumulative=True, append=True)

# help(affb.ta)
df.ta.indicators() # List of all indicators

# Help about the log_return indicator
help(ta.log_return)
# Take a peek
df.tail()

Pandas TA - Technical Analysis Indicators - v0.1.97b
Total Indicators: 117
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_doji, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, decreasing, dema, donchian, dpo, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hl2, hlc3, hma, ichimoku, increasing, inertia, kama, kc, kdj, kst, kurtosis, linear_decay, linreg, log_return, long_run, macd, mad, massi, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvt, pwma, qstick, quantile, rma, roc, rsi, rvgi, rvi, short_run, sinwma, skew, slope, sma, squeeze, stdev, stoch, supertrend, swma, t3, tema, trend_return, trima, trix, true_range, tsi, ttm_trend, ui, uo, variance, vortex, vp, vwap, vwma, wcp, willr, wma, zlma, zscore
Help on function log_return in module pandas_ta.performance.log_return:

log_return(close, length=None, cumulative=False, offset=None, **kwargs)
    Log Return

    Calculates the logarithmic return of a Series.
    See also: help(df.ta.log_return) for additional **kwargs a valid 'df'.

    Sources:
        https://stackoverflow.com/questions/31287552/logarithmic-returns-in-pandas-dataframe

    Calculation:
        Default Inputs:
            length=1, cumulative=False
        LOGRET = log( close.diff(periods=length) )
        CUMLOGRET = LOGRET.cumsum() if cumulative

    Args:
        close (pd.Series): Series of 'close's
        length (int): It's period.  Default: 20
        cumulative (bool): If True, returns the cumulative returns.  Default: False
        offset (int): How many periods to offset the result.  Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.

,open,high,low,close,adj_close,volume,CUMLOGRET_1,CUMPCTRET_1
date,,,,,,,,
2020-08-14,262.31,262.65,258.68,261.24,261.24,14792700,1.563393,1.904450
2020-08-17,262.50,264.10,259.40,261.16,261.16,13351100,1.563087,1.904144
2020-08-18,260.95,265.15,259.26,262.34,262.34,18690400,1.567595,1.908662
2020-08-19,261.39,267.91,261.35,262.59,262.59,23291500,1.568547,1.909615
2020-08-20,261.50,269.63,261.46,269.01,269.01,20299700,1.592702,1.934064

In [6]:
affb[~affb.ta.sma(2).isna()]

              open    high     low   close  adj_close    volume  CUMLOGRET_1  CUMPCTRET_1
date
2014-01-15   57.98   58.57   57.27   57.60      57.60  33663400     0.051476     0.054093
2014-01-16   57.26   58.02   56.83   57.19      57.19  34541800     0.044333     0.046975
2014-01-17   57.30   57.82   56.07   56.30      56.30  40849200     0.028648     0.031413
2014-01-21   56.60   58.58   56.50   58.51      58.51  48669200     0.067151     0.070667
2014-01-22   58.85   59.31   57.10   57.51      57.51  61352900     0.049912     0.053576
...            ...     ...     ...     ...        ...       ...          ...          ...
2020-08-14  262.31  262.65  258.68  261.24     261.24  14792700     1.563393     1.904450
2020-08-17  262.50  264.10  259.40  261.16     261.16  13351100     1.563087     1.904144
2020-08-18  260.95  265.15  259.26  262.34     262.34  18690400     1.567595     1.908662
2020-08-19  261.39  267.91  261.35  262.59     262.59  23291500     1.568547     1.909615
2020-08-20  261.50  269.63  261.46  269.01     269.01  20299700     1.592702     1.934064

[1662 rows x 8 columns]

In [10]:
AllStrategy = ta.AllStrategy
AllStrategy.name

'All'

In [30]:
import sqlalchemy
engine = get_engine()

isinstance(engine,sqlalchemy.engine.base.Engine)

True

# Strategy

## Load data

In [8]:

engine = get_engine()
watch = Watchlist(tickers=['FB'],ds=engine)
watch.load( verbose = True)

here is the engine
[!] Loading All: FB
[+] Strategy: Common Price and Volume SMAs
[i] Indicator arguments: {'timed': False, 'append': True}
[i] Total indicators: 5
[i] Columns added: 5

In [10]:
import pandas_ta as ta
volmas_price_ma_chain = [
    {"kind":"ema", "close": "volume", "length": 10, "prefix": "VOLUME"},
    {"kind":"sma", "close": "volume", "length": 20, "prefix": "VOLUME"},
    {"kind":"ema", "length": 5},
    {"kind":"linreg", "close": "EMA_5", "length": 8, "prefix": "EMA_5"},
]
vp_ma_chain_ta = ta.Strategy("Volume MAs and Price MA chain", volmas_price_ma_chain)
vp_ma_chain_ta

Strategy(name='Volume MAs and Price MA chain', ta=[{'kind': 'ema', 'close': 'volume', 'length': 10, 'prefix': 'VOLUME'}, {'kind': 'sma', 'close': 'volume', 'length': 20, 'prefix': 'VOLUME'}, {'kind': 'ema', 'length': 5}, {'kind': 'linreg', 'close': 'EMA_5', 'length': 8, 'prefix': 'EMA_5'}], description=None, created='10/11/2020, 09:45:05', last_run=None, run_time=None)

In [11]:
# Update the Watchlist
watch.strategy = vp_ma_chain_ta
watch.strategy.name

'Volume MAs and Price MA chain'

In [12]:
watch.load('FB')

import FB
True

,open,high,low,close,adj_close,volume,symbol,date,VOLUME_EMA_10,VOLUME_SMA_20,EMA_5,EMA_5_LR_8
0,27.44,28.18,27.42,28.00,28.00,69846400,FB,2013-01-02,NaN,NaN,NaN,NaN
1,27.88,28.47,27.59,27.77,27.77,63140600,FB,2013-01-03,NaN,NaN,NaN,NaN
2,28.01,28.93,27.83,28.76,28.76,72715400,FB,2013-01-04,NaN,NaN,NaN,NaN
3,28.69,29.79,28.65,29.42,29.42,83781800,FB,2013-01-07,NaN,NaN,NaN,NaN
4,29.51,29.60,28.86,29.06,29.06,45871300,FB,2013-01-08,NaN,NaN,28.602000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1943,247.54,249.95,244.13,248.15,248.15,24709400,FB,2020-09-21,2.625559e+07,27566280.0,256.927276,260.884726
1944,253.31,255.32,248.22,254.75,254.75,30293100,FB,2020-09-22,2.698968e+07,27896655.0,256.201518,258.414817
1945,246.50,252.24,245.62,249.53,249.53,20006800,FB,2020-09-24,2.572007e+07,26790635.0,253.977678,255.940473
1946,255.26,257.99,248.15,249.02,249.02,19641300,FB,2020-09-23,2.461484e+07,26906655.0,252.325119,253.723490
1947,249.40,255.75,246.61,254.82,254.82,18336400,FB,2020-09-25,2.347330e+07,26964855.0,253.156746,252.960978

# MACD BBANDS

In [13]:
# Set BBANDS's 'close' to MACD's main signal, in this case 'MACD_12_26_9' and add a prefix (or suffix) so it's easier to identify
macd_bands_ta = [
    {"kind":"macd"},
    {"kind":"bbands", "close": "MACD_12_26_9", "length": 20, "prefix": "MACD"}
]
macd_bands_ta = ta.Strategy("MACD BBands", macd_bands_ta, f"BBANDS_{macd_bands_ta[1]['length']} applied to MACD")
macd_bands_ta

Strategy(name='MACD BBands', ta=[{'kind': 'macd'}, {'kind': 'bbands', 'close': 'MACD_12_26_9', 'length': 20, 'prefix': 'MACD'}], description='BBANDS_20 applied to MACD', created='10/11/2020, 09:45:05', last_run=None, run_time=None)

In [14]:

# Update the Watchlist
watch.strategy = macd_bands_ta
watch.strategy.name

'MACD BBands'

In [16]:
watch.load("FB")

import FB
True

,open,high,low,close,adj_close,volume,symbol,date,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,MACD_BBL_20_2.0,MACD_BBM_20_2.0,MACD_BBU_20_2.0
0,27.44,28.18,27.42,28.00,28.00,69846400,FB,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN
1,27.88,28.47,27.59,27.77,27.77,63140600,FB,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN
2,28.01,28.93,27.83,28.76,28.76,72715400,FB,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN
3,28.69,29.79,28.65,29.42,29.42,83781800,FB,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN
4,29.51,29.60,28.86,29.06,29.06,45871300,FB,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1943,253.31,255.32,248.22,254.75,254.75,30293100,FB,2020-09-22,-2.040488,-4.577725,2.537237,-2.249155,7.518935,17.287025
1944,255.26,257.99,248.15,249.02,249.02,19641300,FB,2020-09-23,-3.250211,-4.629958,1.379747,-3.947812,6.899253,17.746317
1945,247.54,249.95,244.13,248.15,248.15,24709400,FB,2020-09-21,-4.230361,-4.488087,0.257726,-5.634943,6.242427,18.119798
1946,246.50,252.24,245.62,249.53,249.53,20006800,FB,2020-09-24,-4.839991,-4.078173,-0.761818,-7.225173,5.531878,18.288930
1947,249.40,255.75,246.61,254.82,254.82,18336400,FB,2020-09-25,-4.840470,-3.262922,-1.577548,-8.518739,4.716339,17.951416

# Comprehensive Strategy

## MACD and RSI Momentum with BBANDS and SMAs and Cumulative Log Returns

In [88]:
momo_bands_sma_ta = [
    {"kind":"sma", "length": 50},
    {"kind":"sma", "length": 200},
    {"kind":"bbands", "length": 20},
    {"kind":"macd"},
    {"kind":"squeeze"},
    {"kind":"rsi"},
    {"kind":"log_return", "cumulative": True},
    {"kind":"sma", "close": "CUMLOGRET_1", "length": 5, "suffix": "CUMLOGRET"},
]
momo_bands_sma_strategy = ta.Strategy(
    "Momo, Bands and SMAs and Cumulative Log Returns", # name
    momo_bands_sma_ta, # ta
    "MACD and RSI Momo with BBANDS and SMAs 50 & 200 and Cumulative Log Returns" # description
)
momo_bands_sma_strategy

Strategy(name='Momo, Bands and SMAs and Cumulative Log Returns', ta=[{'kind': 'sma', 'length': 50}, {'kind': 'sma', 'length': 200}, {'kind': 'bbands', 'length': 20}, {'kind': 'macd'}, {'kind': 'squeeze'}, {'kind': 'rsi'}, {'kind': 'log_return', 'cumulative': True}, {'kind': 'sma', 'close': 'CUMLOGRET_1', 'length': 5, 'suffix': 'CUMLOGRET'}], description='MACD and RSI Momo with BBANDS and SMAs 50 & 200 and Cumulative Log Returns', created='10/24/2020, 01:33:50', last_run=None, run_time=None)

In [86]:
watch = Watchlist(tickers=['MSFT'],ds=engine)
watch.load( verbose = True)

[!] Loading All: MSFT
[+] Strategy: Common Price and Volume SMAs
[i] Indicator arguments: {'timed': False, 'append': True}
[i] Total indicators: 5
[i] Columns added: 5

In [89]:

# Update the Watchlist
watch.strategy = momo_bands_sma_strategy
watch.strategy.name

'Momo, Bands and SMAs and Cumulative Log Returns'

In [90]:
fb = watch.load("MSFT")
# Apply constants to the DataFrame for indicators
fb.ta.constants(True, [0, 30, 70])
fb.columns

Index(['open', 'high', 'low', 'close', 'adj_close', 'volume', 'symbol', 'date',
       'SMA_50', 'SMA_200', 'BBL_20_2.0', 'BBM_20_2.0', 'BBU_20_2.0',
       'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'SQZ_20_2.0_20_1.5',
       'SQZ_ON', 'SQZ_OFF', 'SQZ_NO', 'RSI_14', 'CUMLOGRET_1',
       'SMA_5_CUMLOGRET', '0', '30', '70'],
      dtype='object')

In [91]:
fb[['SQZ_20_2.0_20_1.5', 'SQZ_ON', 'SQZ_OFF', 'SQZ_NO']]

      SQZ_20_2.0_20_1.5  SQZ_ON  SQZ_OFF  SQZ_NO
0                   NaN       0        0       1
1                   NaN       0        0       1
2                   NaN       0        0       1
3                   NaN       0        0       1
4                   NaN       0        0       1
...                 ...     ...      ...     ...
1960          12.476665       0        1       0
1961          10.131665       0        1       0
1962          10.983333       0        1       0
1963          12.043333       0        1       0
1964           9.871665       0        1       0

[1965 rows x 4 columns]

# Additional Strategy Options

The params keyword takes a tuple as a shorthand to the parameter arguments in order.

Note: If the indicator arguments change, so will results. Breaking Changes will always be posted on the README.
The col_numbers keyword takes a tuple specifying which column to return if the result is a DataFrame.

In [23]:
params_ta = [
    {"kind":"ema", "params": (10,)},
    # params sets MACD's keyword arguments: fast=9, slow=19, signal=10
    # and returning the 2nd column: histogram
    {"kind":"macd", "params": (9, 19, 10), "col_numbers": (1,)},
    # Selects the Lower and Upper Bands and renames them LB and UB, ignoring the MB
    {"kind":"bbands", "col_numbers": (0,2), "col_names": ("LB", "UB")},
    {"kind":"log_return", "params": (5, False)},
]
params_ta_strategy = ta.Strategy(
    "EMA, MACD History, Outter BBands, Log Returns", # name
    params_ta, # ta
    "EMA, MACD History, BBands(LB, UB), and Log Returns Strategy" # description
)

# Update the Watchlist
watch.strategy = params_ta_strategy
watch.load("FB")

import FB
True

,open,high,low,close,adj_close,volume,symbol,date,EMA_10,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,LOGRET_1
0,27.44,28.18,27.42,28.00,28.00,69846400,FB,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27.88,28.47,27.59,27.77,27.77,63140600,FB,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008248
2,28.01,28.93,27.83,28.76,28.76,72715400,FB,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.035029
3,28.69,29.79,28.65,29.42,29.42,83781800,FB,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.022689
4,29.51,29.60,28.86,29.06,29.06,45871300,FB,2013-01-08,NaN,NaN,NaN,NaN,27.202543,28.602,30.001457,-0.012312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1943,246.50,252.24,245.62,249.53,249.53,20006800,FB,2020-09-24,263.759327,-2.324267,-4.803691,2.479424,242.753154,257.402,272.050846,-0.020978
1944,247.54,249.95,244.13,248.15,248.15,24709400,FB,2020-09-21,260.921268,-3.529477,-4.807121,1.277644,241.575479,253.710,265.844521,-0.005546
1945,255.26,257.99,248.15,249.02,249.02,19641300,FB,2020-09-23,258.757401,-4.364106,-4.513399,0.149294,240.147740,253.008,265.868260,0.003500
1946,253.31,255.32,248.22,254.75,254.75,30293100,FB,2020-09-22,258.028782,-4.511190,-3.728387,-0.782803,244.732028,251.254,257.775972,0.022749
1947,249.40,255.75,246.61,254.82,254.82,18336400,FB,2020-09-25,257.445367,-4.569433,-3.029304,-1.540129,244.732028,251.254,257.775972,0.000275

# Pytorch

In [39]:
start = "2014-01-01"
end = "2020-08-20"
conn = psycopg2.connect(host="slave",
                        database="testdb1",
                        user="postgres",
                        password="reallyStrongPwd123")
cursor = conn.cursor()
symbols = ("MSFT", "GOOGL", "FB")
query2 = f""" SELECT * from incertae."StockData" where symbol in {symbols} and date between '{start}' AND '{end}' """
df = pd.read_sql_query(query2, con=conn)
df.set_index(["date", "symbol"], inplace=True)
df = df.unstack()
df.columns = df.columns.values
y= df[('high', 'FB')].shift(1)
x=df.drop(('high', 'FB'),axis=1)
y = y.fillna(0)

N, D_in, D_out = 100, df.shape[1]-1, 1
class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(input_size,output_size)
    
    def forward(self, X):
        out = self.linear(X)
        return out
model = LinearRegression(D_in, D_out)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)
for epoch in range(100):
    inputs = Variable(torch.from_numpy( x.values)).float()
    labels = Variable(torch.from_numpy( y.values)).float()
    optimizer.zero_grad()

    outputs = model(inputs)

    loss = criterion(outputs,labels)
    loss.backward()
    optimizer.step()

In [25]:
inputs.shape

torch.Size([1671, 17])

In [44]:
    predicted = model(Variable(torch.from_numpy(x.values)).float())

In [43]:
with torch.no_grad():
    predicted = model(Variable(torch.from_numpy(x.values)).float())
    print(predicted)

tensor([[nan],
        [nan],
        [nan],
        ...,
        [nan],
        [nan],
        [nan]])

In [38]:
loss

tensor(1.1586e+14, grad_fn=<MseLossBackward>)

In [47]:
# create dummy data for training
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
class linearRegression(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(linearRegression, self).__init__()
        self.linear = torch.nn.Linear(inputSize, outputSize)

    def forward(self, x):
        out = self.linear(x)
        return out
inputDim = 1        # takes variable 'x' 
outputDim = 1       # takes variable 'y'
learningRate = 0.01 
epochs = 100

model = linearRegression(inputDim, outputDim)
##### For GPU #######
if torch.cuda.is_available():
    model.cuda()
criterion = torch.nn.MSELoss() 
optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)
for epoch in range(epochs):
    # Converting inputs and labels to Variable
    if torch.cuda.is_available():
        inputs = Variable(torch.from_numpy(x_train).cuda())
        labels = Variable(torch.from_numpy(y_train).cuda())
    else:
        inputs = Variable(torch.from_numpy(x_train))
        labels = Variable(torch.from_numpy(y_train))

    # Clear gradient buffers because we don't want any gradient from previous epoch to carry forward, dont want to cummulate gradients
    optimizer.zero_grad()

    # get output from the model, given the inputs
    outputs = model(inputs)

    # get loss for the predicted output
    loss = criterion(outputs, labels)
    print(loss)
    # get gradients w.r.t to parameters
    loss.backward()

    # update parameters
    optimizer.step()

    print('epoch {}, loss {}'.format(epoch, loss.item()))

tensor(128.7580, grad_fn=<MseLossBackward>)
epoch 0, loss 128.7580108642578
tensor(10.5120, grad_fn=<MseLossBackward>)
epoch 1, loss 10.5120267868042
tensor(0.8670, grad_fn=<MseLossBackward>)
epoch 2, loss 0.8669695258140564
tensor(0.0801, grad_fn=<MseLossBackward>)
epoch 3, loss 0.08014492690563202
tensor(0.0159, grad_fn=<MseLossBackward>)
epoch 4, loss 0.015860892832279205
tensor(0.0105, grad_fn=<MseLossBackward>)
epoch 5, loss 0.010513232089579105
tensor(0.0100, grad_fn=<MseLossBackward>)
epoch 6, loss 0.00997408851981163
tensor(0.0098, grad_fn=<MseLossBackward>)
epoch 7, loss 0.009828353300690651
tensor(0.0097, grad_fn=<MseLossBackward>)
epoch 8, loss 0.009715796448290348
tensor(0.0096, grad_fn=<MseLossBackward>)
epoch 9, loss 0.009606998413801193
tensor(0.0095, grad_fn=<MseLossBackward>)
epoch 10, loss 0.009499729610979557
tensor(0.0094, grad_fn=<MseLossBackward>)
epoch 11, loss 0.009393606334924698
tensor(0.0093, grad_fn=<MseLossBackward>)
epoch 12, loss 0.00928875058889389
tensor(0.0092, grad_fn=<MseLossBackward>)
epoch 13, loss 0.009185021743178368
tensor(0.0091, grad_fn=<MseLossBackward>)
epoch 14, loss 0.00908241979777813
tensor(0.0090, grad_fn=<MseLossBackward>)
epoch 15, loss 0.008981051854789257
tensor(0.0089, grad_fn=<MseLossBackward>)
epoch 16, loss 0.00888073816895485
tensor(0.0088, grad_fn=<MseLossBackward>)
epoch 17, loss 0.008781605400145054
tensor(0.0087, grad_fn=<MseLossBackward>)
epoch 18, loss 0.008683527819812298
tensor(0.0086, grad_fn=<MseLossBackward>)
epoch 19, loss 0.008586570620536804
tensor(0.0085, grad_fn=<MseLossBackward>)
epoch 20, loss 0.00849066860973835
tensor(0.0084, grad_fn=<MseLossBackward>)
epoch 21, loss 0.008395860902965069
tensor(0.0083, grad_fn=<MseLossBackward>)
epoch 22, loss 0.008302085101604462
tensor(0.0082, grad_fn=<MseLossBackward>)
epoch 23, loss 0.00820935983210802
tensor(0.0081, grad_fn=<MseLossBackward>)
epoch 24, loss 0.00811772234737873
tensor(0.0080, grad_fn=<MseLossBackward>)
epoch 25, loss 0.008027071133255959
tensor(0.0079, grad_fn=<MseLossBackward>)
epoch 26, loss 0.007937457412481308
tensor(0.0078, grad_fn=<MseLossBackward>)
epoch 27, loss 0.007848788052797318
tensor(0.0078, grad_fn=<MseLossBackward>)
epoch 28, loss 0.007761133834719658
tensor(0.0077, grad_fn=<MseLossBackward>)
epoch 29, loss 0.007674464490264654
tensor(0.0076, grad_fn=<MseLossBackward>)
epoch 30, loss 0.0075887637212872505
tensor(0.0075, grad_fn=<MseLossBackward>)
epoch 31, loss 0.007504050619900227
tensor(0.0074, grad_fn=<MseLossBackward>)
epoch 32, loss 0.0074202255345880985
tensor(0.0073, grad_fn=<MseLossBackward>)
epoch 33, loss 0.007337347138673067
tensor(0.0073, grad_fn=<MseLossBackward>)
epoch 34, loss 0.007255473639816046
tensor(0.0072, grad_fn=<MseLossBackward>)
epoch 35, loss 0.0071744234301149845
tensor(0.0071, grad_fn=<MseLossBackward>)
epoch 36, loss 0.00709434924647212
tensor(0.0070, grad_fn=<MseLossBackward>)
epoch 37, loss 0.0070151062682271
tensor(0.0069, grad_fn=<MseLossBackward>)
epoch 38, loss 0.006936777848750353
tensor(0.0069, grad_fn=<MseLossBackward>)
epoch 39, loss 0.006859269458800554
tensor(0.0068, grad_fn=<MseLossBackward>)
epoch 40, loss 0.006782672833651304
tensor(0.0067, grad_fn=<MseLossBackward>)
epoch 41, loss 0.006706990767270327
tensor(0.0066, grad_fn=<MseLossBackward>)
epoch 42, loss 0.006632054224610329
tensor(0.0066, grad_fn=<MseLossBackward>)
epoch 43, loss 0.0065579949878156185
tensor(0.0065, grad_fn=<MseLossBackward>)
epoch 44, loss 0.006484786048531532
tensor(0.0064, grad_fn=<MseLossBackward>)
epoch 45, loss 0.006412321235984564
tensor(0.0063, grad_fn=<MseLossBackward>)
epoch 46, loss 0.006340759806334972
tensor(0.0063, grad_fn=<MseLossBackward>)
epoch 47, loss 0.00626993365585804
tensor(0.0062, grad_fn=<MseLossBackward>)
epoch 48, loss 0.00619991822168231
tensor(0.0061, grad_fn=<MseLossBackward>)
epoch 49, loss 0.00613071583211422
tensor(0.0061, grad_fn=<MseLossBackward>)
epoch 50, loss 0.0060622673481702805
tensor(0.0060, grad_fn=<MseLossBackward>)
epoch 51, loss 0.005994541570544243
tensor(0.0059, grad_fn=<MseLossBackward>)
epoch 52, loss 0.005927566904574633
tensor(0.0059, grad_fn=<MseLossBackward>)
epoch 53, loss 0.005861407611519098
tensor(0.0058, grad_fn=<MseLossBackward>)
epoch 54, loss 0.005795991513878107
tensor(0.0057, grad_fn=<MseLossBackward>)
epoch 55, loss 0.005731245968490839
tensor(0.0057, grad_fn=<MseLossBackward>)
epoch 56, loss 0.005667222198098898
tensor(0.0056, grad_fn=<MseLossBackward>)
epoch 57, loss 0.005603942088782787
tensor(0.0055, grad_fn=<MseLossBackward>)
epoch 58, loss 0.005541377700865269
tensor(0.0055, grad_fn=<MseLossBackward>)
epoch 59, loss 0.0054795038886368275
tensor(0.0054, grad_fn=<MseLossBackward>)
epoch 60, loss 0.005418301094323397
tensor(0.0054, grad_fn=<MseLossBackward>)
epoch 61, loss 0.005357787478715181
tensor(0.0053, grad_fn=<MseLossBackward>)
epoch 62, loss 0.005297947209328413
tensor(0.0052, grad_fn=<MseLossBackward>)
epoch 63, loss 0.005238817539066076
tensor(0.0052, grad_fn=<MseLossBackward>)
epoch 64, loss 0.005180298816412687
tensor(0.0051, grad_fn=<MseLossBackward>)
epoch 65, loss 0.0051224688068032265
tensor(0.0051, grad_fn=<MseLossBackward>)
epoch 66, loss 0.005065246485173702
tensor(0.0050, grad_fn=<MseLossBackward>)
epoch 67, loss 0.0050087179988622665
tensor(0.0050, grad_fn=<MseLossBackward>)
epoch 68, loss 0.004952752031385899
tensor(0.0049, grad_fn=<MseLossBackward>)
epoch 69, loss 0.00489745894446969
tensor(0.0048, grad_fn=<MseLossBackward>)
epoch 70, loss 0.004842773545533419
tensor(0.0048, grad_fn=<MseLossBackward>)
epoch 71, loss 0.004788689780980349
tensor(0.0047, grad_fn=<MseLossBackward>)
epoch 72, loss 0.004735197406262159
tensor(0.0047, grad_fn=<MseLossBackward>)
epoch 73, loss 0.004682349041104317
tensor(0.0046, grad_fn=<MseLossBackward>)
epoch 74, loss 0.004630046896636486
tensor(0.0046, grad_fn=<MseLossBackward>)
epoch 75, loss 0.0045783319510519505
tensor(0.0045, grad_fn=<MseLossBackward>)
epoch 76, loss 0.004527213051915169
tensor(0.0045, grad_fn=<MseLossBackward>)
epoch 77, loss 0.004476678557693958
tensor(0.0044, grad_fn=<MseLossBackward>)
epoch 78, loss 0.004426665138453245
tensor(0.0044, grad_fn=<MseLossBackward>)
epoch 79, loss 0.004377223085612059
tensor(0.0043, grad_fn=<MseLossBackward>)
epoch 80, loss 0.004328374285250902
tensor(0.0043, grad_fn=<MseLossBackward>)
epoch 81, loss 0.00428001768887043
tensor(0.0042, grad_fn=<MseLossBackward>)
epoch 82, loss 0.004232227336615324
tensor(0.0042, grad_fn=<MseLossBackward>)
epoch 83, loss 0.00418495386838913
tensor(0.0041, grad_fn=<MseLossBackward>)
epoch 84, loss 0.004138266667723656
tensor(0.0041, grad_fn=<MseLossBackward>)
epoch 85, loss 0.004092030227184296
tensor(0.0040, grad_fn=<MseLossBackward>)
epoch 86, loss 0.004046339076012373
tensor(0.0040, grad_fn=<MseLossBackward>)
epoch 87, loss 0.004001127555966377
tensor(0.0040, grad_fn=<MseLossBackward>)
epoch 88, loss 0.00395646458491683
tensor(0.0039, grad_fn=<MseLossBackward>)
epoch 89, loss 0.0039122807793319225
tensor(0.0039, grad_fn=<MseLossBackward>)
epoch 90, loss 0.003868628991767764
tensor(0.0038, grad_fn=<MseLossBackward>)
epoch 91, loss 0.0038253848906606436
tensor(0.0038, grad_fn=<MseLossBackward>)
epoch 92, loss 0.003782691666856408
tensor(0.0037, grad_fn=<MseLossBackward>)
epoch 93, loss 0.00374044943600893
tensor(0.0037, grad_fn=<MseLossBackward>)
epoch 94, loss 0.003698707325384021
tensor(0.0037, grad_fn=<MseLossBackward>)
epoch 95, loss 0.0036573901306837797
tensor(0.0036, grad_fn=<MseLossBackward>)
epoch 96, loss 0.0036165579222142696
tensor(0.0036, grad_fn=<MseLossBackward>)
epoch 97, loss 0.003576137125492096
tensor(0.0035, grad_fn=<MseLossBackward>)
epoch 98, loss 0.003536197356879711
tensor(0.0035, grad_fn=<MseLossBackward>)
epoch 99, loss 0.0034967265091836452